config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "/artist_dashboard", to: "pages#artist_dashboard", as: :artist_dashboard
  get "/discover", to: "users#discover", as: :discover
  get "/analytics", to: "pages#analytics", as: :analytics
  get "/edit_portfolio", to: "pages#edit_portfolio", as: :edit_portfolio
  get "/my_events", to: "events#my_events", as: :my_events
  get "/joined_events", to: "events#joined_events", as: :joined_events
  get "/canvas", to: "artworks#canvas", as: :canvas
  get "/canvas/new", to: "artworks#new_canvas", as: :new_canvas
  get "/banners", to: "artworks#banners", as: :banners
  post "/add_banner", to: "users#add_banner", as: :add_banner
  delete "/delete_banner/:id", to: "users#delete_banner", as: :delete_banner

  resources :events do
    resources :event_attendances, only: %i[new create]
  end
  resources :event_attendances, only: %i[index show destroy]
  resources :subscriptions, only: %i[index]
  resources :subscriber_groups, only: %i[index show create destroy] do
    post "/new_broadcast", to: "subscriber_groups#new_broadcast", as: :new_broadcast
  end
  resources :artworks, only: %i[index new create update destroy]
  resources :artworks, only: %i[edit] do
    resources :art_details, only: %i[update create destroy]
  end
  resources :users, only: %i[index show update] do
    resources :subscriptions, only: %i[create]
    resources :conversations, only: %i[create]
    resources :preferences, only: %i[create]
    member do
      get :preferences
    end
  end
  resources :subscriptions, only: %i[destroy]
  resources :conversations, only: %i[index show create] do
    resources :messages, only: %i[create]
  end
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :user
  has_many :art_details, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :user, presence: true
  validates :has_details, inclusion: { in: [true, false] }

  has_one_attached :photo
  has_many_attached :details_photos # probably remove this (move to artdetails)

  STYLES = [
    'Expressionism',
    'Cubism',
    'Dadaism',
    'Impressionism',
    'Minimalism',
    'Pointillism',
    'Pop',
    'Surrealism',
    'Symbolism']

  TITLES = [
    "Ethereal Dreams",
    "Aurora's Embrace",
    "Serenade in Blue",
    "Whispers of Twilight",
    "Abstract Reverie",
    "Crimson Cascade",
    "Dance of the Fireflies",
    "Reflections of Solitude",
    "Emerald Enchantment",
    "Infinite Horizons",
    "Sunset Sonata",
    "Mystic Waters",
    "Harmony of Chaos",
    "Tranquil Whispers",
    "Urban Mirage",
    "Celestial Harmony",
    "Enchanted Forest",
    "Midnight Serenity",
    "Sapphire Secrets",
    "Journey to Elysium",
    "Aetherial Allure",
    "Echoes of the Cosmos",
    "Rhapsody in Red",
    "Whispers in the Wind",
    "Emerging Hues",
    "Melodies of the Mind",
    "Aqua Dreamscape",
    "Crimson Reverie",
    "Silent Solitude",
    "Tranquil Echoes",
    "Azure Dreams",
    "Luminous Overture",
    "Gossamer Shadows",
    "Rhapsody in Purple",
    "Enchanted Evening",
    "Harmony of Colors",
    "Cerulean Dreams",
    "Nebula's Embrace",
    "Whispers of Dawn",
    "Mystic Voyage",
    "Dreams of Dusk",
  ]

  DESCRIPTIONS = [
    "This exquisite painting captures a serene lakeside scene at dawn, with the gentle ripples of the water reflecting the soft hues of the rising sun.",
    "A mesmerizing abstract composition that invites viewers to lose themselves in a sea of vibrant colors and intricate patterns.",
    "In this stunning landscape, the artist skillfully portrays the rugged grandeur of a mountain range under a dramatic, cloud-filled sky.",
    "A surreal masterpiece that transports the observer to a dreamlike realm, where reality and fantasy coalesce in a vivid, imaginative landscape.",
    "Vivid and daring, this painting's bold use of crimson and deep blues creates a visceral sense of passion and intensity.",
    "An intimate portrayal of a single red rose, its delicate petals seeming to glow with an inner luminance against a dark background.",
    "A thought-provoking artwork that challenges the viewer's perceptions, encouraging introspection and contemplation.",
    "Energetic and dynamic, this canvas pulsates with life, its riotous mix of colors and shapes exuding boundless creativity.",
    "Step into a realm of enchantment with this ethereal dreamscape, where reality blurs and the imagination takes flight.",
    "A captivating portrayal of a celestial dance, as the moon and sun appear to waltz across the canvas, casting a mesmerizing spell.",
    "This contemplative piece invites viewers to ponder the complexities of existence, with its intricate details and symbolic elements.",
    "Geometry and aesthetics converge in a mesmerizing display of balance and precision, creating a harmonious visual experience.",
    "Minimalism at its finest, this painting employs clean lines and subtle shades to convey simplicity and sophistication.",
    "A whirlwind of vibrant colors and swirling forms infuses this canvas with a sense of dynamism and vitality.",
    "Journey through time with this artwork, which weaves together moments from history into a beautifully intricate tapestry.",
    "Explore the enchanting underwater world in this whimsical composition, where marine life thrives amidst a vivid coral reef.",
    "This portrait is a profound study of the human soul, capturing the subject's innermost thoughts and emotions.",
    "In this surreal landscape, reality blurs as dreamlike elements coalesce, inviting viewers into a world of wonder and curiosity.",
    "The interplay of light and shadow creates a sense of drama and depth in this captivating study of contrasts.",
    "An intimate still life composition that imbues ordinary objects with newfound significance and poetic beauty."
  ]
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    @artworks = current_user.artworks.where(has_details: false)
    @title = "My Artworks"
  end

  def canvas
    @canvas = current_user.artworks.where(has_details: true)
    @title = "My Canvas"
  end

  def banners
    @artist = current_user
    @banners = current_user.banners
    @title = "My Banners"
  end

  def new
    @artwork = Artwork.new
    @title = "New Artwork"
  end

  def new_canvas
    @canvas = Artwork.new
    @canvas.has_details = true
    @title = "New Canvas"
  end

  def edit
    @artwork = Artwork.find(params[:id])
    @art_detail = ArtDetail.new
    @title = @artwork.has_details? ? "Edit Canvas" : "Edit Artwork"
  end

  def update
    @artwork = Artwork.find(params[:id])
    @artwork.update(artwork_params)
    redirect_to @artwork.has_details? ? canvas_path : artworks_path
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user
    @artwork.save!
    redirect_to @artwork.has_details? ? edit_artwork_path(@artwork) : artworks_path
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    redirect_to @artwork.has_details? ? canvas_path : artworks_path
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :description, :style, :has_details, :photo)
  end
end

app/views/artworks/_card_artwork.html.erb
<div class="card-artwork">
  <div class="card-artwork-info">
    <h2><%= artwork.title %></h2>
    <p><%= artwork.description %></p>
  </div>
  <%= cl_image_tag artwork.photo.key, class: "card-artwork-photo" %>
  <div class="card-artwork-buttons">
    <%= link_to "Edit", edit_artwork_path(artwork), class: "button" %>
    <%= link_to "Delete", artwork_path(artwork), data: { turbo_method: :delete, turbo_confirm: "Are you sure that you want to delete this artwork?"}, class: "button" %>
  </div>
</div>

app/views/artworks/_card_canvas.html.erb
<div class="card-artwork">
  <div class="card-artwork-info">
    <h2><%= canvas.title %></h2>
    <p><%= canvas.description %></p>
  </div>
  <%= cl_image_tag canvas.photo.key, class: "card-artwork-photo" %>
  <div class="card-artwork-buttons">
    <%= link_to "Edit", edit_artwork_path(canvas), class: "button" %>
    <%= link_to "Delete", artwork_path(canvas), data: { turbo_method: :delete, turbo_confirm: "Are you sure that you want to delete this canvas?"}, class: "button" %>
  </div>
</div>

app/views/artworks/banners.html.erb
<div class="artist-btn-box">
  <div data-controller="pop-up">
    <div data-action="click->pop-up#showPopup">
      <%= link_to "Add Banner", banners_path, class: "artist-btn" %>
    </div>
    <div class="popup" data-pop-up-target="box">
      <div style="text-align: center; padding: 25px 0;">
        <h4>Add Banner</h4>
      </div>
      <div>
        <%= simple_form_for @artist, url: add_banner_path, method: :post do |f| %>
          <div class="d-flex">
            <%= f.input :banners, as: :file,
            label: false,
            wrapper_html: {style: "width: 100%;"}
            %>
          </div>
          <div class="form-group" style="display: flex; margin: 25px 0;">
            <%= f.button :submit, "Save", class: "button", style: "margin: 20px auto 0 auto;"%>
          </div>
        <% end %>
      </div>
      <span class="close" data-action="click->pop-up#closePopup">&times;</span>
    </div>
  </div>
</div>
<div class="container-m">
  <div class ="grid-artworks">
    <% @banners.each_with_index do |banner, index| %>
      <div class="card-artwork">
        <div class="card-artwork-info">
          <h2><%= "Banner #{index + 1}" %></h2>
        </div>
        <%= cl_image_tag banner.key, class: "card-artwork-photo" %>
        <div class="card-artwork-buttons">
          <%= link_to "Delete", delete_banner_path(banner), data: { turbo_method: :delete, turbo_confirm: "Are you sure that you want to delete this banner?"}, class: "button" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/artworks/canvas.html.erb
<div class="artist-btn-box">
  <%= link_to "Add Canvas", new_canvas_path, class: "artist-btn" %>
</div>
<div class="container-m">
  <div class ="grid-artworks">
    <% @canvas.each do |canvas| %>
      <%= render "artworks/card_canvas", canvas: canvas %>
    <% end %>
  </div>
</div>

app/views/artworks/edit.html.erb
<% if @artwork.has_details? == false %>
  <div class="container-l">
    <div class="container-edit-artwork">
      <div class="artwork-photo">
        <%= cl_image_tag @artwork.photo.key %>
      </div>
      <div class="artwork-infos">
        <h2><%= @artwork.title %></h2>
        <%= simple_form_for(@artwork) do |f| %>
          <%= f.input :title %>
          <%= f.input :description %>
          <%= f.input :style, as: :select, collection: Artwork::STYLES %>
          <div style="display: flex; margin: 25px 0;">
            <%= f.button :submit, @artwork.has_details? ? "Update Canvas" : "Update Artwork" ,class: "button", style: "margin: 20px auto 0 auto;"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% if @artwork.has_details? %>
  <div class="container-m pb-0">
    <div class="text-center mb-2">
      <h2><%= @artwork.title %></h2>
    </div>
    <div class="artwork-map-container">
      <%= cl_image_tag @artwork.photo.key, style: "position: relative", class: "artwork-map" %>
      <% ArtDetail::COORDINATE_COUNT.times do |x| %>
        <% ArtDetail::COORDINATE_COUNT.times do |y| %>
          <%= render "users/empty_art_detail_marker", artwork: @artwork, x_index: x, y_index: y %>
        <% end %>
      <% end %>
      <% @artwork.art_details.each do |art_detail| %>
        <%= render "users/art_detail_marker", art_detail: art_detail %>
      <% end %>
    </div>

  </div>
  <div class="container-m px-1">
    <%= simple_form_for(@artwork) do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :style, as: :select, collection: Artwork::STYLES %>
      <div style="display: flex; margin: 25px 0;">
        <%= f.button :submit, @artwork.has_details? ? "Update Canvas" : "Update Artwork" ,class: "button", style: "margin: 20px auto 0 auto;"%>
      </div>
    <% end %>
  </div>
<% end %>

app/views/artworks/index.html.erb
<div class="artist-btn-box">
  <%= link_to "Add Artwork", new_artwork_path, class: "artist-btn" %>
</div>
<div class="container-m">
  <div class ="grid-artworks">
    <% @artworks.each do |artwork| %>
      <%= render "artworks/card_artwork", artwork: artwork %>
    <% end %>
  </div>
</div>

app/views/artworks/new.html.erb
<div class="container-l">
  <div class="container-edit-artwork">
    <div class="artwork-photo">
      <div class="artwork-photo-placeholder">
        <i class='fa-regular fa-plus'></i>
        <p>add an image file</p>
      </div>
    </div>
    <div class="artwork-infos">
      <%= simple_form_for(@artwork) do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :style, include_blank: "Select", collection: Artwork::STYLES %>
        <%= f.input :photo, as: :file, label: "Artwork" %>
        <%= f.hidden_field :has_details, value: false %>
        <div style="display: flex; margin: 25px 0;">
          <%= f.button :submit, class: "button", style: "margin: 20px auto 0 auto;"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/artworks/new_canvas.html.erb
<div class="container-s px-1" style="height: calc(100vh - 300px);">
  <%= simple_form_for(@canvas) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :style, include_blank: "Select", collection: Artwork::STYLES %>
    <%= f.input :photo, as: :file, label: "Canvas" %>
    <%= f.hidden_field :has_details, value: true %>
    <div style="display: flex; margin: 25px 0;">
      <%= f.button :submit, "Start", class: "button", style: "margin: 20px auto 0 auto;"%>
    </div>
  <% end %>
</div>