config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "/artist_dashboard", to: "pages#artist_dashboard", as: :artist_dashboard
  get "/discover", to: "users#discover", as: :discover
  get "/analytics", to: "pages#analytics", as: :analytics
  get "/edit_portfolio", to: "pages#edit_portfolio", as: :edit_portfolio
  get "/my_events", to: "events#my_events", as: :my_events
  get "/joined_events", to: "events#joined_events", as: :joined_events
  get "/canvas", to: "artworks#canvas", as: :canvas
  get "/canvas/new", to: "artworks#new_canvas", as: :new_canvas
  get "/banners", to: "artworks#banners", as: :banners
  post "/add_banner", to: "users#add_banner", as: :add_banner
  delete "/delete_banner/:id", to: "users#delete_banner", as: :delete_banner

  resources :events do
    resources :event_attendances, only: %i[new create]
  end
  resources :event_attendances, only: %i[index show destroy]
  resources :subscriptions, only: %i[index]
  resources :subscriber_groups, only: %i[index show create destroy] do
    post "/new_broadcast", to: "subscriber_groups#new_broadcast", as: :new_broadcast
  end
  resources :artworks, only: %i[index new create update destroy]
  resources :artworks, only: %i[edit] do
    resources :art_details, only: %i[update create destroy]
  end
  resources :users, only: %i[index show update] do
    resources :subscriptions, only: %i[create]
    resources :conversations, only: %i[create]
    resources :preferences, only: %i[create]
    member do
      get :preferences
    end
  end
  resources :subscriptions, only: %i[destroy]
  resources :conversations, only: %i[index show create] do
    resources :messages, only: %i[create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :send_welcome_email
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :artworks, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :event_attendances, dependent: :destroy
  has_many :preferences, dependent: :destroy
  has_many :subscriptions, foreign_key: :buyer_id, class_name: 'Subscription', dependent: :destroy
  has_many :received_subscriptions, foreign_key: :artist_id, class_name: 'Subscription', dependent: :destroy
  has_many :conversations, foreign_key: :buyer_id, class_name: 'Conversation', dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :received_conversations, foreign_key: :artist_id, class_name: 'Conversation', dependent: :destroy
  has_many :subscriber_groups, dependent: :destroy
  has_many :group_attendances, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  validates :is_artist, inclusion: { in: [true, false] }

  # validates :location, if: :is_artist?, presence: true
  # validates :short_bio, if: :is_artist?, presence: true
  # validates :long_bio, if: :is_artist?, presence: true

  has_one_attached :avatar
  has_many_attached :banners

  SHORT_BIOS = [
    "Exploring the world through colors and shapes.",
    "Creating art that speaks to the soul.",
    "Expressing emotions on canvas, one stroke at a time.",
    "Pushing the boundaries of creativity to inspire.",
    "Transforming ideas into visual masterpieces."
  ]


  LONG_BIOS = [
    "I am an accomplished and internationally recognized artist with a lifelong commitment to exploring the profound depths of human emotion through my work. Over the course of my career, I have received numerous awards and accolades for my contributions to the art world. My paintings are a reflection of the intricate tapestry of life's complexities, where I meticulously layer colors and textures to convey a myriad of emotions and experiences. Each piece is a visual narrative, often juxtaposing light and dark, inviting viewers to delve into the rich and intricate stories I weave onto the canvas. My art seeks to provoke thought and spark dialogue about the human condition, inviting viewers to connect with their own emotions and experiences on a deeply personal level.",
    "As an artist, I find endless inspiration in the natural world that surrounds us. Nature's beauty and serenity serve as a constant muse for my creative endeavors. With a deep appreciation for landscapes and wildlife, I strive to capture the essence of these wonders in my art. Through my brush strokes and color palettes, I aim to convey not only the visual splendor of the world but also the emotional resonance it elicits within me. My goal is to share this sense of wonder and awe with the world, inviting viewers to connect with the natural world and its boundless beauty through my creations.",
    "My artistic journey is a fusion of classical traditions and avant-garde concepts. With a rich cultural heritage and a deep appreciation for the arts, I draw from centuries of artistic wisdom while infusing my work with modern and contemporary ideas. The result is a body of work that is both rooted in tradition and pushing the boundaries of what art can be. I seek to challenge conventional norms and provoke thought, using my art as a vehicle for social commentary and cultural exploration. My pieces often invite viewers to question their assumptions, inviting them to engage in a dialogue about the ever-evolving world of art and its role in our lives.",
    "With a background in architecture, my art is marked by geometric precision and an exploration of spatial relationships. My fascination lies in the interplay of shapes, colors, and forms within a given space. I use my art to invite viewers to reconsider their perception of the physical world around them. My compositions are carefully crafted to evoke a sense of harmony and balance, drawing from the principles of architectural design. Each piece is a testament to my passion for creating art that challenges the viewer's spatial awareness and invites them to explore the intricate dance between geometry and aesthetics.",
    "I am a versatile multimedia artist who thrives on the boundless possibilities of creative experimentation. My portfolio encompasses a wide range of mediums, from traditional painting and sculpture to cutting-edge digital art and immersive mixed-media installations. My work is a testament to my commitment to pushing the boundaries of what art can be and how it can engage with its audience. I believe that art is a dynamic and evolving force that transcends traditional categorizations, and I invite viewers to journey with me through the ever-expanding landscape of artistic expression."
  ]

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
#   # before_action :configure_sign_up_params, only: [:create]
#   # before_action :configure_account_update_params, only: [:update]

#   # GET /resource/sign_up
#   # def new
#   #   super
#   # end

#   # POST /resource
#   # def create
#   #   super
#   # end

#   # GET /resource/edit
#   # def edit
#   #   super
#   # end

#   # PUT /resource
#   # def update
#   #   super
#   # end

#   # DELETE /resource
#   # def destroy
#   #   super
#   # end

#   # GET /resource/cancel
#   # Forces the session data which is usually expired after sign
#   # in to be expired now. This is useful if the user wants to
#   # cancel oauth signing in/up in the middle of the process,
#   # removing all OAuth session data.
#   # def cancel
#   #   super
#   # end

#   protected

#   # def user_params
#   #   params.require(:user).permit(:first_name, :last_name, :email, :encrypted_password)
#   # end

#   # If you have extra params to permit, append them to the sanitizer.
#   # def configure_sign_up_params
#   #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
#   # end

#   # If you have extra params to permit, append them to the sanitizer.
#   # def configure_account_update_params
#   #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
#   # end

#   # The path used after sign up.
#   # def after_sign_up_path_for(resource)
#   #   super(resource)
#   # end

#   # The path used after sign up for inactive accounts.
#   # def after_inactive_sign_up_path_for(resource)
#   #   super(resource)
#   # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @hide_nav_footer = true
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def discover
    @title = "Discover"
    @banner = "user3_avatar.jpg"
    @preferences = Preference.where(user: current_user).pluck(:style)
    if @preferences.empty?
      @artists = User.where(is_artist: true).shuffle
    else
      @artists = User.joins(:artworks).where(artworks: { style: @preferences }).distinct
    end
  end

  def index
    @artists = User.where(is_artist: true)
    @title = "Your Artists"
    @banner = "user1_avatar.jpg"

    if params[:query].present?
      # @artists = @artists.where("first_name ILIKE ?", "%#{params[:query]}%")
      sql_subquery = "first_name ILIKE :query OR last_name ILIKE :query"
      @artists = @artists.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @artist = User.find(params[:id])
    @subscription = Subscription.find_by(buyer: current_user, artist: @artist)
    @conversation = Conversation.find_by(buyer: current_user, artist: @artist)
    @banner = @artist.banners
    @hide_artist_buttons = true if current_user.is_artist?
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to edit_portfolio_path
  end

  def preferences
    @hide_nav_footer = true
    @preference = Preference.new
  end

  def delete_banner
    @banner = ActiveStorage::Attachment.find(params[:id])
    @banner.purge
    redirect_to banners_path
  end

  def add_banner
    @artist = current_user
    @banner = params[:user][:banners]
    @artist.banners.attach(@banner)
    redirect_to banners_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :short_bio, :long_bio, :avatar)
  end
end

app/views/users/_art_detail_marker.html.erb
<div data-controller="pop-up">
  <div data-action="click->pop-up#showPopup" >
    <div class="white-marker" style="position: absolute; left: calc(<%= art_detail.x_value %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %>); bottom: calc(<%= art_detail.y_value %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %>);"></div>
  </div>
  <div class="detail-popup" data-pop-up-target="box" style="position: absolute; left: calc(<%= art_detail.x_value %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %> + 30px); bottom: calc(<%= art_detail.y_value %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %> + 30px);">
    <div style="text-align: center;">
      <h4><%= art_detail.title %></h4>
      <p><%= art_detail.description %></p>
    </div>
    <span class="close" data-action="click->pop-up#closePopup">&times;</span>
  </div>
</div>

app/views/users/_artist_card.html.erb
<%= link_to user_path(artist), class: "artist-card" do %>
  <div class="artist-card-img">
    <%= cl_image_tag artist.avatar.key %>
  </div>
  <div class="text">
    <h2><%= artist.first_name %></h2>
    <p><%= artist.long_bio.truncate(300) %></p>
    <p><strong>Styles</strong>
      · <% artist.artworks.pluck(:style).uniq.each do |style| %>
        <%= style %> ·
      <% end %>
    </p>
  </div>
<% end %>

app/views/users/_artist_card_flip.html.erb
<%= link_to user_path(artist), class: "artist-card flip" do %>
<%# style: "margin: auto 0 60px auto;"  %>
  <div class="text">
    <h2><%= artist.first_name %></h2>
    <p><%= artist.long_bio.truncate(300) %></p>
    <p><strong>Styles</strong>
      · <% artist.artworks.pluck(:style).uniq.each do |style| %>
        <%= style %> ·
      <% end %>
    </p>
  </div>
  <div class="artist-card-img">
    <%= cl_image_tag artist.avatar.key %>
  </div>
<% end %>

app/views/users/_banner_aubergine.html.erb
<div class="banner-aubergine">
  <div class="container-l">
    <div class="artworks-grid">
      <% artworks.each do |artwork| %>
        <div class="artwork-card">
          <%= cl_image_tag artwork.photo.key %>
          <div class="text">
            <h4><%= artwork.title %></h4>
            <p><%= artwork.description %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_empty_art_detail_marker.html.erb
<div data-controller="pop-up">
  <div data-action="click->pop-up#showPopup" >
    <div class="empty-marker" style="position: absolute; left: calc(<%= x_index %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %>); bottom: calc(<%= y_index %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %>);"></div>
  </div>
  <div class="detail-popup" data-pop-up-target="box" style="position: absolute; left: calc(<%= x_index %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %> + 30px); bottom: calc(<%= y_index %> * (100% - 15px) / <%= ArtDetail::COORDINATE_COUNT - 1 %> + 30px);">
    <%= simple_form_for @art_detail, url: artwork_art_details_path(artwork), method: :post do |f| %>
      <%= f.input :title, wrapper_html: {style: "width: 100%;"} %>
      <%= f.input :description, wrapper_html: {style: "width: 100%;"} %>
      <%= f.hidden_field :x_value, value: x_index %>
      <%= f.hidden_field :y_value, value: y_index %>
    <div class="form-group" style="display: flex;">
      <%= f.button :submit, "Save", class: "button", style: "margin: 0 auto;"%>
    </div>
    <% end %>
    <span class="close" data-action="click->pop-up#closePopup">&times;</span>
  </div>
</div>

app/views/users/discover.html.erb
<div class="container-l">
  <% @artists.each_with_index do |artist, index| %>
    <% if index.even? %><%= render "users/artist_card", artist: artist %><% end %>
    <% if index.odd? %><%= render "users/artist_card_flip", artist: artist %><% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container-l">
  <div class="event-search-box">
    <div class="form-row">
      <%= form_with url: users_path, method: :get, class: "d-flex gap-2" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Find an Artist..."
            %>
        <%= submit_tag "Search", name: "", class: "warm-gray-btn" %>
      <% end %>
    </div>
  </div>
  <% @artists.each_with_index do |artist, index| %>
    <% if index.even? %><%= render "users/artist_card", artist: artist %><% end %>
    <% if index.odd? %><%= render "users/artist_card_flip", artist: artist %><% end %>
  <% end %>
</div>

app/views/users/preferences.html.erb
<div class="devise-flex">
  <div>
    <%= link_to root_path, class: "homepage-logo" do %>
      <%= image_tag "logo_white.png" %>
    <% end %>
  </div>
  <div class="warm-gray-container-600">
    <h2>Welcome to Regal Art.</h2>
    <p>Please tell us more about your favourite art styles, this will help us introduce you to the artists who might be more relevant to you.</p>

    <%= simple_form_for [current_user, @preference], label: false, legend: false do |f| %>
      <div class="style-box">
      <%= f.input :style, as: :check_boxes,
                  collection: Preference::STYLES,
                  label: false,
                  wrapper: false,
                  input_html: { class: 'style' } %>
      </div>
      <div class="devise-center mt-5">
      <%= f.button :submit, value: "Explore your artists", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% unless @hide_artist_buttons %>
  <div class="artist-btn-box">
    <div class="artist-btn">Artist Journey</div>
    <% if @subscription %>
      <%= link_to "Connected <i class='fa-solid fa-check'></i>".html_safe, subscription_path(@subscription), data: { turbo_method: :delete }, class: "artist-btn" %>
      <% if @conversation %>
        <%= link_to "<i class='fa-regular fa-message'></i>".html_safe, conversation_path(@conversation), class: "artist-btn-message" %>
      <% else %>
        <%= link_to "<i class='fa-regular fa-message'></i>".html_safe, user_conversations_path(@artist), data: { turbo_method: :post }, class: "artist-btn-message" %>
      <% end %>
    <% else %>
    <%= link_to "Connect", user_subscriptions_path(@artist), data: { turbo_method: :post }, class: "artist-btn" %>
    <% end %>
  </div>
<% end %>

<div class="container-l">
  <div class="container-artist-bio">
    <%= cl_image_tag @artist.avatar.key, class: "avatar", style: "opacity: 1;" %>
    <div class="bio">
      <h2><%= @artist.short_bio %></h2>
      <p><%= @artist.long_bio %></p>
    </div>
  </div>
</div>

<%= render "shared/video_card" %>

<div class="container-l">
  <h2>Discover the Artist's Latest Artistic Endeavors</h2>
  <%= render "shared/carousel" %>
</div>

<%= render "users/banner_aubergine", artworks: @artist.artworks.where(has_details: false) %>

<div class="container-l mt-4">
  <h2>Explore <%= @artist.artworks.where(has_details: true).first.title %></h2>
  <div class="artwork-map-container">
    <%= cl_image_tag @artist.artworks.where(has_details: true).first.photo.key, style: "position: relative", class: "artwork-map" %>
    <% @artist.artworks.where(has_details: true).first.art_details.each do |art_detail| %>
      <%= render "users/art_detail_marker", art_detail: art_detail %>
    <% end %>
  </div>
</div>