config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "/artist_dashboard", to: "pages#artist_dashboard", as: :artist_dashboard
  get "/discover", to: "users#discover", as: :discover
  get "/analytics", to: "pages#analytics", as: :analytics
  get "/edit_portfolio", to: "pages#edit_portfolio", as: :edit_portfolio
  get "/my_events", to: "events#my_events", as: :my_events
  get "/joined_events", to: "events#joined_events", as: :joined_events
  get "/canvas", to: "artworks#canvas", as: :canvas
  get "/canvas/new", to: "artworks#new_canvas", as: :new_canvas
  get "/banners", to: "artworks#banners", as: :banners
  post "/add_banner", to: "users#add_banner", as: :add_banner
  delete "/delete_banner/:id", to: "users#delete_banner", as: :delete_banner

  resources :events do
    resources :event_attendances, only: %i[new create]
  end
  resources :event_attendances, only: %i[index show destroy]
  resources :subscriptions, only: %i[index]
  resources :subscriber_groups, only: %i[index show create destroy] do
    post "/new_broadcast", to: "subscriber_groups#new_broadcast", as: :new_broadcast
  end
  resources :artworks, only: %i[index new create update destroy]
  resources :artworks, only: %i[edit] do
    resources :art_details, only: %i[update create destroy]
  end
  resources :users, only: %i[index show update] do
    resources :subscriptions, only: %i[create]
    resources :conversations, only: %i[create]
    resources :preferences, only: %i[create]
    member do
      get :preferences
    end
  end
  resources :subscriptions, only: %i[destroy]
  resources :conversations, only: %i[index show create] do
    resources :messages, only: %i[create]
  end
end

app/views/shared/_carousel.html.erb
<div class="carousel-box" data-controller="carousel">
  <div class="carousel-container-nb" data-carousel-target="container">
    <% @artist.artworks.each_with_index do |artwork, index| %>
      <%= cl_image_tag artwork.photo.key, data: { carousel_target: "slide" }, class: "slide-nb #{"active" if index.zero?}" %>
    <% end %>
  </div>

  <div class="carousel-btns">
    <button data-action="click->carousel#previous">
      <i class="fa-solid fa-angle-down fa-rotate-90 fa-2xl"></i>
    </button>
    <button data-action="click->carousel#next">
      <i class="fa-solid fa-angle-down fa-rotate-270 fa-2xl"></i>
    </button>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-container">
    <p>Contact us at ducks@regal-art.com</p>
    <p>© 2021 Regal Art</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<% if banner.nil? %>
  <% img = image_url("user1_avatar.jpg") %>
<% end %>
<% if banner.class == String %>
  <% img = image_url(banner) %>
<% end %>
<% if banner.class == ActiveStorage::Attached::Many %>
  <% img = cl_image_path(banner.last.key) %>
<% end %>
<div class="navbar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= img %>)">
  <div class="navbar-top">
    <div class="navbar-logo">
      <%= link_to discover_path do %>
        <%= image_tag "logo_white.png" %>
      <% end %>
    </div>
    <div class="navbar-bar">
      <ul>
        <li class="nav-item">
            <%= link_to "Discover", discover_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Artists", users_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path %>
          </li>
          <li class="nav-item dropdown" data-controller="reveal" data-action="mouseout->reveal#hide">
            <%= link_to @user, "#", data: {action: "mouseover->reveal#display"} %>
            <div class="dropdown-m" data-reveal-target="item" >
              <%= link_to "My Artists", subscriptions_path %><br>
              <%= link_to "My Events", "#" %><br>
              <%= link_to "Preferences", "#" %><br>
              <%= link_to "Conversations", conversations_path %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "font-weight-bold" %>
            </div>
          </li>
      </ul>
    </div>
  </div>
  <div class="navbar-heading" style="">
    <h1><%= title %></h1>
  </div>
</div>

app/views/shared/_navbar_artist.erb
<% if banner.nil? %>
  <% img = image_url("user1_avatar.jpg") %>
<% end %>
<% if banner.class == String %>
  <% img = image_url(banner) %>
<% end %>
<% if banner.class == ActiveStorage::Attached::Many %>
  <% img = cl_image_path(banner.last.key) %>
<% end %>
<div class="navbar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= img %>)">
  <div class="navbar-top">
    <div class="navbar-logo">
      <%= link_to artist_dashboard_path do %>
        <%= image_tag "logo_white.png" %>
      <% end %>
    </div>
    <div class="navbar-bar">
      <ul>
        <li class="nav-item">
            <%= link_to "Dashboard", artist_dashboard_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Conversations", conversations_path %>
          </li>
          <li class="nav-item">
            <%= link_to "My Events", my_events_path %>
          </li>
          <li class="nav-item dropdown" data-controller="reveal" data-action="mouseout->reveal#hide">
            <a data-action="mouseover->reveal#display" href="<%= artist_dashboard_path %>"><i class="fa-solid fa-circle-user"></i></a>
            <div class="dropdown-m" data-reveal-target="item" >
              <%= link_to "Portfolio", edit_portfolio_path %><br>
              <%= link_to "Subscribers", subscriber_groups_path %><br>
              <%= link_to "Analytics", analytics_path %><br>
              <%= link_to "Settings", edit_user_registration_path %><br>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
  <div class="navbar-bottom">
    <div class="navbar-heading" style="">
      <h1><%= title %></h1>
    </div>
  </div>
</div>

app/views/shared/_navbar_buyer.html.erb
<% if banner.nil? %>
  <% img = image_url("user1_avatar.jpg") %>
<% end %>
<% if banner.class == String %>
  <% img = image_url(banner) %>
<% end %>
<% if banner.class == ActiveStorage::Attached::Many %>
  <% img = cl_image_path(banner.last.key) %>
<% end %>
<div class="navbar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= img %>)">
  <div class="navbar-top">
    <div class="navbar-logo">
      <%= link_to discover_path do %>
        <%= image_tag "logo_white.png" %>
      <% end %>
    </div>
    <div class="navbar-bar">
      <ul>
        <li class="nav-item">
            <%= link_to "Discover", discover_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Artists", users_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Conversations", conversations_path %>
          </li>
          <li class="nav-item dropdown" data-controller="reveal" data-action="mouseout->reveal#hide">
            <a data-action="mouseover->reveal#display" href="<%= dashboard_path %>"><i class="fa-solid fa-circle-user"></i></a>
            <div class="dropdown-m" data-reveal-target="item" >
              <%= link_to "Dashboard", dashboard_path %><br>
              <%= link_to "Subscriptions", subscriptions_path %><br>
              <%= link_to "My events", joined_events_path %><br>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
  <div class="navbar-bottom">
    <div class="navbar-heading">
      <h1><%= title %></h1>
    </div>
  </div>
</div>

app/views/shared/_video_card.html.erb
<div class="video-box">
  <%= video_tag("video_1.mp4", id: "video-background", controls: false, autoplay: true, muted: true, loop: true) %>
  <div class="video-card">
    <h2>Transcendence: Boundaries of Reality</h2>
    <p>In this captivating artist project, the artist's unique vision comes to life with a compelling blend of creativity and skill. Drawing from personal experiences and a deep well of inspiration, the artist delves into the intricacies of human emotion and the human condition. Through a masterful use of color, texture, and form, the project immerses viewers in a world of raw and unfiltered expression. It's a testament to the artist's ability to distill complex ideas into visual storytelling, offering a profound and thought-provoking experience that lingers long after one has encountered their work.</p>
  </div>
</div>