config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard", as: :dashboard
  get "/artist_dashboard", to: "pages#artist_dashboard", as: :artist_dashboard
  get "/discover", to: "users#discover", as: :discover
  get "/analytics", to: "pages#analytics", as: :analytics
  get "/edit_portfolio", to: "pages#edit_portfolio", as: :edit_portfolio
  get "/my_events", to: "events#my_events", as: :my_events
  get "/joined_events", to: "events#joined_events", as: :joined_events
  get "/canvas", to: "artworks#canvas", as: :canvas
  get "/canvas/new", to: "artworks#new_canvas", as: :new_canvas
  get "/banners", to: "artworks#banners", as: :banners
  post "/add_banner", to: "users#add_banner", as: :add_banner
  delete "/delete_banner/:id", to: "users#delete_banner", as: :delete_banner

  resources :events do
    resources :event_attendances, only: %i[new create]
  end
  resources :event_attendances, only: %i[index show destroy]
  resources :subscriptions, only: %i[index]
  resources :subscriber_groups, only: %i[index show create destroy] do
    post "/new_broadcast", to: "subscriber_groups#new_broadcast", as: :new_broadcast
  end
  resources :artworks, only: %i[index new create update destroy]
  resources :artworks, only: %i[edit] do
    resources :art_details, only: %i[update create destroy]
  end
  resources :users, only: %i[index show update] do
    resources :subscriptions, only: %i[create]
    resources :conversations, only: %i[create]
    resources :preferences, only: %i[create]
    member do
      get :preferences
    end
  end
  resources :subscriptions, only: %i[destroy]
  resources :conversations, only: %i[index show create] do
    resources :messages, only: %i[create]
  end
end

app/views/pages/analytics.html.erb
<div class="container-l">
  <div class="analytics-intro">
    <div>
      <h3><%= "#{@user.first_name} #{@user.last_name}" %></h3>
      <p><%= @user.short_bio %></p>
    </div>
    <div class="interactions-container">
      <div class="analytics-box">
        <p>Connections</p>
        <h4><%= @subscribers %></h4>
      </div>
      <div class="analytics-box">
        <p>Events</p>
        <h4><%= @events %></h4>
      </div>
      <div class="analytics-box">
        <p>Conversations</p>
        <h4><%= @conversations %></h4>
      </div>
    </div>
  </div>
  <div class="growth-rate-box">
    <div class="growth-rate">
      <p><i class="fa-solid fa-chart-line"></i></p>
      <h3><%= @subscriber_growth_rate %>%</h3>
      <p>Connections Growth Rate (90 days)</p>
    </div>
    <div class="growth-rate">
      <p><i class="fa-solid fa-chart-line"></i></p>
      <h3><%= @conversations_growth_rate %>%</h3>
      <p>Conversations Growth Rate (90 days)</p>
    </div>
  </div>
  <h4>New Connections Per Week</h4>
  <div class="chart container-l">
    <br>
    <%= line_chart Subscription.group_by_week(:created_at).count, download: {background: "#ffffff", filename: "Gained Connections per Week" } %>
  </div>
  <hr>
  <div class="chart-box container-l">
    <div>
      <h4>Average Number of Attendees per Event</h4>
      <div class="chart">
        <br>
        <%= column_chart @average_attendances_per_month, download: {background: "#ffffff", filename: "Average Number of Attendees per Event"} %>
      </div>
    </div>
    <div>
      <h4>Connections Turned into Conversations</h4>
      <div class="chart">
        <br>
        <%= pie_chart @pie_chart_data, download: {background: "#ffffff", filename: "Connections turned into Conversations"} %>
      </div>
    </div>
  </div>
</div>

app/views/pages/artist_dashboard.html.erb
<div class="container-l">
  <div class="dashboard-grid-3">
    <%= link_to edit_portfolio_path, class: "dashboard-card dashboard-button" do %>
      <h4>Portfolio</h4>
      <p>Edit content on your profile</p>
    <% end %>
    <%= link_to subscriber_groups_path, class: "dashboard-card dashboard-button" do %>
      <h4>Subscribers</h4>
      <p>Manage the users subscribed to you</p>
    <% end %>
    <%= link_to analytics_path, class: "dashboard-card dashboard-button" do %>
      <h4>Analytics</h4>
      <p>See Analytics of your profile</p>
    <% end %>
    <%= link_to conversations_path, class: "dashboard-card dashboard-button" do %>
      <h4>Conversations</h4>
      <p>Speak to your subscribers</p>
    <% end %> <!-- change to logged in user -->
    <%= link_to my_events_path, class: "dashboard-card dashboard-button" do %>
      <h4>My Events</h4>
      <p>Manage your events</p>
    <% end %>
    <%= link_to edit_user_registration_path, class: "dashboard-card dashboard-button" do %>
      <h4>Settings</h4>
      <p>Account-Preferences</p>
    <% end %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container-l">
  <div class="dashboard-grid-4">
    <%= link_to edit_user_registration_path, class: "dashboard-card dashboard-button" do %>
      <h4>Profile</h4>
      <p>Edit your preferences and personal information</p>
    <% end %>
    <%= link_to subscriptions_path, class: "dashboard-card dashboard-button" do %>
      <h4>Subscriptions</h4>
      <p>All your favourite artists</p>
    <% end %>
    <%= link_to joined_events_path, class: "dashboard-card dashboard-button" do %>
      <h4>My Events</h4>
      <p>The events you want to attend</p>
    <% end %>
    <%= link_to conversations_path, class: "dashboard-card dashboard-button" do %>
      <h4>Conversations</h4>
      <p>Between you and the artist</p>
    <% end %>
  </div>
</div>

app/views/pages/edit_portfolio.html.erb
<div class="artist-btn-box">
  <%= link_to "View Profile", user_path(@artist), class: "artist-btn" %>
</div>
<div class="container-m">
  <div class="card-portfolio">
    <div>
      <h2>Profile</h2>
      <div data-controller="pop-up">
        <div data-action="click->pop-up#showPopup">
          <%= link_to "Edit <i class='fa-regular fa-pen-to-square'></i>".html_safe, edit_portfolio_path, class: "portfolio-button" %>
        </div>
        <div class="popup" data-pop-up-target="box">
          <div style="text-align: center; padding: 25px 0;">
            <h4>Profile</h4>
          </div>
          <div>
            <%= simple_form_for(@artist) do |f| %>
              <div style="display: flex; flex-direction: column;">
                <div class="d-flex justify-content-between">
                  <%= f.input :first_name %>
                  <%= f.input :last_name %>
                </div>
                <%= f.input :short_bio,
                input_html: {style: "height: 50px;"},
                wrapper_html: {style: "width: 100%;"}
                %>
                <%= f.input :avatar, as: :file %>
              </div>
            <div class="form-group" style="display: flex; margin: 25px 0;">
              <%= f.button :submit, "Save", class: "button", style: "margin: 20px auto 0 auto;"%>
            </div>
            <% end %>
          </div>
          <span class="close" data-action="click->pop-up#closePopup">&times;</span>
        </div>
      </div>
    </div>
    <div class="profile">
      <div style="margin-right: 20px;">
        <h4><%= "#{@artist.first_name} #{@artist.last_name}" %></h4>
        <p><%= @artist.short_bio %></p>
      </div>
      <%= cl_image_tag @artist.avatar.key %>
    </div>
  </div>
  <div class="card-portfolio">
    <div>
      <h2>Description</h2>
      <div data-controller="pop-up">
        <div data-action="click->pop-up#showPopup">
          <%= link_to "Edit <i class='fa-regular fa-pen-to-square'></i>".html_safe, edit_portfolio_path, class: "portfolio-button" %>
        </div>
        <div class="popup" data-pop-up-target="box">
          <div style="text-align: center; padding: 25px 0;">
            <h4>Description</h4>
          </div>
          <div>
            <%= simple_form_for(@artist) do |f| %>
              <div class="d-flex">
                <%= f.input :long_bio,
                label: false,
                wrapper_html: {style: "width: 100%;"}
                %>
              </div>
            <div class="form-group" style="display: flex; margin: 25px 0;">
              <%= f.button :submit, "Save", class: "button", style: "margin: 20px auto 0 auto;"%>
            </div>
            <% end %>
          </div>
          <span class="close" data-action="click->pop-up#closePopup">&times;</span>
        </div>
      </div>
    </div>
    <div class="portfolio-text">
      <p><%= @artist.long_bio %></p>
    </div>
  </div>
  <div class="card-portfolio">
    <div>
      <h2>Banners</h2>
      <%= link_to "Manage <i class='fa-solid fa-list'></i>".html_safe, banners_path, class: "portfolio-button" %>
    </div>
    <div class="artworks">
      <% @artist.banners.each do |banner| %>
        <%= cl_image_tag banner.key %>
      <% end %>
    </div>
  </div>
  <div class="card-portfolio">
    <div>
      <h2>Artworks</h2>
      <%= link_to "Manage <i class='fa-solid fa-list'></i>".html_safe, artworks_path, class: "portfolio-button" %>
    </div>
    <div class="artworks">
      <% @artist.artworks.where(has_details: false).each do |artwork| %>
        <%= cl_image_tag artwork.photo.key %>
      <% end %>
    </div>
  </div>
  <div class="card-portfolio">
    <div>
      <h2>Canvas</h2>
      <%= link_to "Manage <i class='fa-solid fa-list'></i>".html_safe, canvas_path, class: "portfolio-button" %>
    </div>
    <div class="artworks">
      <% @artist.artworks.where(has_details: true).each do |artwork| %>
        <%= cl_image_tag artwork.photo.key %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= link_to root_path, class: "homepage-logo" do %>
  <%= image_tag "logo_white.png" %>
<% end %>

<div class="homepage-container">
  <div class="homepage-col top-20">
    <div class="homepage-card">
      <%= image_tag("user1_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("artist_6.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user3_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("artist_6.jpg") %>
    </div>
  </div>

  <div class="homepage-col top-120">
    <div class="homepage-card">
      <%= image_tag("artist_7.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user5_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user4_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user2_avatar.jpg") %>
    </div>
  </div>

  <div class="homepage-col top-200">
    <div class="homepage-card">
      <%= image_tag("user2_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user3_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("artist_7.jpg") %>
    </div>
  </div>

  <div class="homepage-col top-150">
    <div class="homepage-card">
      <%= image_tag("user5_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user2_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user1_avatar.jpg") %>
    </div>
  </div>

  <div class="homepage-col top-90">
    <div class="homepage-card">
      <%= image_tag("artist_6.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user4_avatar.jpg") %>
    </div>
    <div class="homepage-card">
      <%= image_tag("user3_avatar.jpg") %>
    </div>
  </div>
</div>

<div class="black-wrapper" data-controller="push-up">
  <div class="wrapper-btns">

    <div class="homepage-btn" data-push-up-target="journey" data-action="click->push-up#hideAndPush">
      <h1>Start your journey</h1>
      <i class="fa-solid fa-angle-down fa-2xl"></i>
    </div>

    <div class="login-signup-box" data-push-up-target="loginSignup">
      <a href="users/sign_up"><div class="signup-btn">
        <i class="fa-solid fa-angle-down fa-rotate-90 fa-2xl"></i>
        <h2>Sign up</h2>
      </div></a>
      <a href="users/sign_in"><div class="login-btn">
        <h2>Log in</h2>
        <i class="fa-solid fa-angle-down fa-rotate-270 fa-2xl"></i>
      </div></a>
    </div>

  </div>
  <div class="black-veil" data-push-up-target="blackveil"></div>
</div>

<div class="purple-veil"></div>